### ISSUE TITLE
The pickup does not appear

### ISSUE THREAD

**Issue by Andonrai** [dockfries/infernus#22]
I'm trying to create a pickup, but it doesn't show up in the game

Used code:
![](https://imgur.com/pIpO9bw.png)

Values ​​returned when creating the pickup:
![](https://imgur.com/dvMnSTz.png)

**Comment by dockfries** [comment]
![image](https://github.com/dockfries/infernus/assets/34953768/b7076a00-656d-4c67-8016-117f520da679)
 Doesn't seem to be a problem


Do you create this object in GameMode's OnInit?
Are the characters in the same world and coordinates?

Remember, everything about the game should be done inside the callback event, not outside it.

Also, the I of modelid in your code should be lowercase, if not the font display problem.

**Comment by Andonrai** [comment]
> ![image](https://user-images.githubusercontent.com/34953768/239696335-b7076a00-656d-4c67-8016-117f520da679.png)
> 
> **There doesn't seem to be an issue.**
> 
> Have you instantiated this object within the GameMode's OnInit function?
> 
> Are the characters located within the same virtual world and coordinates?
> 
> **Please keep in mind that all game-related actions should be performed within the callback event, and not outside of it.**
> 
> Additionally, please note that the `"I"` in `modelid` should be **lowercase**
> 
> ```ts
> const gm = new GameMode();
> gm.onInit = () => {
>   new DynamicPickup({
>     modelid: 19135,
>     type: 1,
>     x: 1536.8569,
>     y: -1688.5819,
>     z: 13.5469,
>     streamdistance: 20,
>     worldid: 0,
>     interiorid: 0,
>   }).create();
> };
> ```

Solved, thank you.
