### ISSUE TITLE
UTF-8 Character Encoding Issue

### ISSUE THREAD

**Issue by cha5e369** [dockfries/infernus#28]
Currently, I’m encountering an issue related to character encoding while compiling the library. It should be able to handle strings containing Hispanic characters (áéíóúñ) with accents or accented characters when using UTF-8, but it seems that this isn’t being achieved correctly.

The workspace encoding within the IDE is set to UTF-8.

Example code:
```ts
import { playerEvent } from "@/controller/player";
import { logger } from "@/logger";
import { MyDialog } from "@/models/dialog";
import { DialogStylesEnum, IDialog } from "@infernus/core";

playerEvent.onCommandText("test", async (player, ...args) => {

  const StringData = `
  Normal characters: aeiou.
  Hispanic characters: áéíóú.
  `;

  const DialogData: IDialog = {
    style: DialogStylesEnum.MSGBOX,
    caption: "Charset issue",
    info: StringData,
    button1: "Close"
  };

  const res = await new MyDialog(DialogData).show(player);

  logger.info(res);

  return true;
});
```
![0EC93C57-4E5D-4549-B89D-B9460E37719D](https://github.com/dockfries/infernus/assets/77559597/b3aebd55-7b10-471e-8f3c-9286cc00772b)

**Comment by dockfries** [comment]
Try to set the player's character set to "iso-8859-1".

**Comment by cha5e369** [comment]
> Try to set the player's character set to "ISO-8859-1".

thanks u!
