### ISSUE TITLE
Broken encode setting mode/language config.

### ISSUE THREAD

**Issue by Frank441** [dockfries/infernus#35]
> This only happens on SAMP legacy launcher (not the open.mp one).

When you want to add a special character in the **language** or **mode** strings, they will break (`config.json` or `GameMode#sendRconCommand`). 

This code below will get the same result even if you try to use [iconv-lite npm](https://www.npmjs.com/package/iconv-lite) encode method with UTF-8, Windows1252 or [ISO-8859-1](https://github.com/dockfries/infernus/issues/28#issuecomment-1793477332).

Example code:
```ts
import { GameMode } from "@infernus/core";

GameMode.onInit(async ({ next }) => {

   GameMode.sendRconCommand("language Español"); // "EspaÃ±ol" as result.

});
```

**Comment by dockfries** [comment]
Will there be this issue if you use the legacy samp client and samp server? That is to say, the above code is written in .pwn code or through the configuration item of server.cfg.

I think it's possible that this issue is caused by the legacy samp client, not by open.mp or infernus.

**Comment by Frank441** [comment]
It seems that something happens behind samp-node that changes differently that string charset.

However, **writing a .pwn filterscript** with **Windows 1252** and **compiling with Pawno** works great (Qawno doesn't work for this because it only supports Windows 1251).

**Comment by dockfries** [comment]
I don't have an environment to test here.
For samp-node, my current encapsulated sendClientMessage layer is achieved by passing "a" and byte arrays, rather than "s" and utf8 strings. I don't know if this works.

```ts
import { GameMode, I18n } from "@infernus/core";

GameMode.onInit(async ({ next }) => {
	const buf = I18n.encodeToBuf("language Español", "win1252");
	samp.callNative("SendRconCommand", "a", buf);
});
```

**Comment by Frank441** [comment]
> I don't have an environment to test here. For samp-node, my current encapsulated sendClientMessage layer is achieved by passing "a" and byte arrays, rather than "s" and utf8 strings. I don't know if this works.
> 
> ```ts
> import { GameMode, I18n } from "@infernus/core";
> 
> GameMode.onInit(async ({ next }) => {
> 	const buf = I18n.encodeToBuf("language Español", "win1252");
> 	samp.callNative("SendRconCommand", "a", buf);
> });
> ```

Works amazing, thanks for sharing this!

**Comment by dockfries** [comment]
I added a charset parameter, upgraded to the latest 0.11.0-beta.6 version and used the following code should be equivalent to the above code.

```ts
import { GameMode } from "@infernus/core";

GameMode.onInit(async ({ next }) => {
   GameMode.sendRconCommand("language Español", "win1252");
});
```
