### ISSUE TITLE
samp-node returning empty strings on player events

### ISSUE THREAD

**Issue by Frank441** [dockfries/infernus#40]
> use my [samp-node](https://github.com/dockfries/samp-node/releases/tag/2.2.0) fork instead of iAmir's.

_Originally posted by @dockfries in https://github.com/dockfries/infernus/issues/39#issuecomment-2185679848_

Example code:
```js
import { PlayerEvent } from "@infernus/core";

PlayerEvent.onDisconnect(({ player, reason, next }) => {
  console.log(player.getName());
});
```

* Expected output: an string with the player's name.
* Received output: an empty string (`'\x00\b'`).

Could it be somehow related to [this commit](https://github.com/AmyrAhmady/samp-node/commit/9ebf07cc70715988ad5280b1721f2bca8d7b5785)?

**Comment by dockfries** [comment]
try update latest core version
