### ISSUE TITLE
Gamemode doesn't work

### ISSUE THREAD

**Issue by goottime** [dockfries/infernus#42]
I tried to install everything according to the documentation. But the gamemode refuses to work, there is a connection to the server, but no further actions are performed, although the infernus-starter gamemode should be executed.
I also discovered that game events are not being processed or executed.
I added a log to OnPlayerConnect, but it did not appear when connecting to the server.
The message is only displayed when OnGamemodeInit and also when OnPlayerDisconnect I received an error.

To install and run I used the following commands:
`pnpm dlx @infernus/create-app create`
`cd projectname`
`infernus install`
`pnpm install`
`pnpm dev`

**Comment by dockfries** [comment]
Since raknet callbacks are not registered by default, rpc and packet are blocked.
your need to complete the raknet environment.

this is `@infernus/create-app` cli tool issue, I will fix it later.

```ts
import { onIncomingPacket, onIncomingRPC, onOutgoingPacket, onOutgoingRPC } from "@infernus/raknet";

onIncomingPacket(({ next }) => {
  return next()
})

onIncomingRPC(({ next }) => {
  return next()
})

onOutgoingPacket(({ next }) => {
  return next()
})

onOutgoingRPC(({ next }) => {
  return next()
})
```
